name: Deploy Guestbook

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Start Minikube
      run: minikube start

    - name: Configure Minikube
      run: minikube update-context

    - name: Deploy Redis Master
      run: |
        kubectl apply -f redis-master-controller.yaml
        kubectl apply -f redis-master-service.yaml

    - name: Deploy Redis Replica
      run: |
        kubectl apply -f redis-replica-controller.yaml
        kubectl apply -f redis-replica-service.yaml

    - name: Deploy Guestbook
      run: |
        kubectl apply -f guestbook-controller.yaml
        kubectl apply -f guestbook-service.yaml

    - name: Verify Deployment
      run: |
        kubectl get pods
        kubectl get services

    - name: Stop Minikube
      run: minikube stop
